#!/usr/bin/env tsx
/**
 * 编译期把 .claude/sop-data/clusters/ 下的 prompts.jsonl + specs/{slug}.json
 * 合并生成 src/shared/blocks/gptimage2studio/clusters-data.ts
 *
 * Cloudflare Workers 不支持运行时 fs，所以打包成纯 TS export。
 * 任何 prompts.jsonl 或 spec.json 改动后必须重跑。
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';

const ROOT_PROJECT =
  '/Users/moxiao/Documents/web-outbound/sites/gptimage2studio-claude-optimize';
const ROOT_DATA = `${ROOT_PROJECT}/.claude/sop-data/clusters`;
const OUTPUT = `${ROOT_PROJECT}/src/shared/blocks/gptimage2studio/clusters-data.ts`;

// 按 P0 优先级排序（与 specs/_summary.md 对齐）
const CLUSTER_ORDER = [
  'action-figure-prompts',         // P0-1 viral
  'old-photo-restore-prompts',     // P0-2 viral
  'instagram-photo-edit-prompts',  // P0-3 viral
  'sticker-prompts',               // P0-4 viral
  'thumbnail-prompts',             // P0-5 viral
  'cinematic-portrait-prompts',    // P0-6 commercial
  'product-photography-prompts',   // P0-7 commercial
  'poster-design-prompts',         // P0-8 creative
  'food-photography-prompts',      // P0-9 commercial
  'infographic-prompts',           // P0-10 creative
];

function readJsonl(path: string): any[] {
  return readFileSync(path, 'utf-8')
    .split('\n')
    .filter((l) => l.trim())
    .map((l) => JSON.parse(l));
}

function readJson(path: string): any {
  return JSON.parse(readFileSync(path, 'utf-8'));
}

function pickPromptFields(r: any) {
  return {
    prompt_id: r.prompt_id,
    title: r.title,
    sub_scene_tag: r.sub_scene_tag ?? null,
    final_prompt: r.final_prompt,
    json_template_ref: r.json_template_ref ?? null,
    input_image_required: !!r.input_image_required,
    estimated_credits: r.estimated_credits ?? 6,
    language: r.language ?? 'en',
    final_image_url: r.final_image_url ?? '',
    final_image_width: r.final_image_width ?? 0,
    final_image_height: r.final_image_height ?? 0,
  };
}

const CJK_RE = /[一-鿿぀-ヿ가-힯]/;

// 字段含 CJK 时返回 null/默认值（避免中文 SOP 笔记污染 SEO HTML）
function safeStr(v: unknown): string | null {
  if (typeof v !== 'string' || !v) return null;
  return CJK_RE.test(v) ? null : v;
}
function safeArr<T extends Record<string, unknown>>(arr: T[] | undefined): T[] {
  if (!Array.isArray(arr)) return [];
  return arr.filter((item) =>
    Object.values(item).every(
      (v) => typeof v !== 'string' || !CJK_RE.test(v),
    ),
  );
}

// 只保留 UI 用到的字段，避免中文 SOP 笔记（search_intent / page_structure_notes）
// 出现在客户端 HTML 源码里污染 SEO。
function pickSpecFields(spec: any) {
  return {
    slug: spec.slug,
    tier: spec.tier,
    h1: spec.h1,
    meta_title: spec.meta_title,
    meta_description: spec.meta_description,
    intro_long: safeStr(spec.intro_long),
    sub_scenes: (spec.sub_scenes || []).map((s: any) => ({
      name: s.name,
      slug_anchor: s.slug_anchor,
      description: safeStr(s.description),
      prompt_count_target: s.prompt_count_target ?? 0,
    })),
    how_it_works: safeArr(spec.how_it_works),
    why_use: safeArr(spec.why_use),
    use_cases: safeArr(spec.use_cases),
    tips: safeArr(spec.tips),
    related_articles: Array.isArray(spec.related_articles)
      ? spec.related_articles.filter(
          (s: unknown) => typeof s === 'string' && !CJK_RE.test(s),
        )
      : [],
    faq: spec.faq || [],
    internal_links: spec.internal_links || [],
  };
}

function main() {
  const banner = `// AUTO-GENERATED by compile-clusters-data.ts. DO NOT EDIT.
// Source: .claude/sop-data/clusters/{slug}/prompts.jsonl + specs/{slug}.json
// Regenerate: npx tsx .claude/sop-data/tools/compile-clusters-data.ts
//
// Last generated: ${new Date().toISOString()}

`;

  const types = `export type PromptItem = {
  prompt_id: string;
  title: string;
  sub_scene_tag: string | null;
  final_prompt: string;
  json_template_ref: string | null;
  input_image_required: boolean;
  estimated_credits: number;
  language: string;
  final_image_url: string;
  final_image_width: number;
  final_image_height: number;
};

export type SubScene = {
  name: string;
  slug_anchor: string;
  description: string | null;
  prompt_count_target: number;
};

export type FaqItem = { q: string; a: string };
export type InternalLink = { to: string; anchor_text: string };
export type StepItem = { title: string; body: string };
export type UseCaseItem = { title: string; body: string };
export type TipItem = { q: string; a: string };

export type ClusterTier = 'viral' | 'commercial' | 'creative';

export type ClusterSpec = {
  slug: string;
  tier: ClusterTier;
  h1: string;
  meta_title: string;
  meta_description: string;
  intro_long: string | null;
  sub_scenes: SubScene[];
  how_it_works: StepItem[];
  why_use: StepItem[];
  use_cases: UseCaseItem[];
  tips: TipItem[];
  related_articles: string[];
  faq: FaqItem[];
  internal_links: InternalLink[];
};

export type Cluster = {
  spec: ClusterSpec;
  prompts: PromptItem[];
};

`;

  // 收集每个 cluster
  const clusters: Record<string, any> = {};
  for (const slug of CLUSTER_ORDER) {
    const promptsPath = `${ROOT_DATA}/${slug}/prompts.jsonl`;
    const specPath = `${ROOT_DATA}/specs/${slug}.json`;
    if (!existsSync(promptsPath)) {
      throw new Error(`prompts.jsonl 不存在: ${promptsPath}`);
    }
    if (!existsSync(specPath)) {
      throw new Error(`spec.json 不存在: ${specPath}`);
    }
    const promptsRaw = readJsonl(promptsPath);
    const specRaw = readJson(specPath);
    clusters[slug] = {
      spec: pickSpecFields(specRaw),
      prompts: promptsRaw.map(pickPromptFields),
    };
  }

  // 验证字段
  let totalPrompts = 0;
  let missingImage = 0;
  for (const slug of CLUSTER_ORDER) {
    const c = clusters[slug];
    totalPrompts += c.prompts.length;
    for (const p of c.prompts) {
      if (!p.final_image_url) missingImage++;
    }
    if (!c.spec.h1) {
      throw new Error(`${slug} spec 缺 h1`);
    }
  }
  console.log(`✓ 收集 ${CLUSTER_ORDER.length} 个 cluster, ${totalPrompts} 条 prompt`);
  if (missingImage > 0) {
    console.warn(`  ⚠ ${missingImage} 条缺 final_image_url`);
  }

  // 生成 export 代码
  const exports: string[] = [];
  exports.push(banner);
  exports.push(types);
  exports.push('export const CLUSTER_ORDER: readonly string[] = [');
  for (const slug of CLUSTER_ORDER) {
    exports.push(`  '${slug}',`);
  }
  exports.push('] as const;');
  exports.push('');
  exports.push('export const PROMPT_CLUSTERS: Record<string, Cluster> = {');
  for (const slug of CLUSTER_ORDER) {
    const json = JSON.stringify(clusters[slug], null, 2)
      .split('\n')
      .map((line, i) => (i === 0 ? line : '  ' + line))
      .join('\n');
    exports.push(`  '${slug}': ${json},`);
  }
  exports.push('};');
  exports.push('');
  exports.push('export const ALL_CLUSTERS: Cluster[] = CLUSTER_ORDER.map((s) => PROMPT_CLUSTERS[s]);');
  exports.push('');

  writeFileSync(OUTPUT, exports.join('\n'));
  const stat = readFileSync(OUTPUT, 'utf-8');
  console.log(`✓ 生成: ${OUTPUT}`);
  console.log(`  文件大小: ${(stat.length / 1024).toFixed(0)} KB`);
}

main();
